config/routes.rb
Rails.application.routes.draw do
  root "demo#index"
  # #simple match route
  get "demo/index"
  get "demo/hello"
  get "demo/about"
  get "demo/contact"

  resources :subjects do
    member do
      get :delete
    end
  end
  resources :pages do
  member do
    get :delete
  end
end
  # get "pages/index"
  # get "pages/show"
  # get "pages/new"
  # get "pages/edit"
  # get "pages/delete"

  # get "subjects/index"
  # get "subjects/show"
  # get "subjects/new"
  # get "subjects/edit"
  # get "subjects/delete"



  # default route
  # get ":controller(/:action(/:id))"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :subject
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :pages
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  layout false

  def index
    # explicit render - most of the time we don't need this and can rely on default behavior
    # render('demo/index')
  end

  def hello
    @array = [ 1, 2, 3, 4, 5 ]
    @id = params["id"]
    @page = params[:page]
    # render('hello')
    # redirect_to(:controller => 'demo', :action => 'index')
  end

  def about
    render("demo/about_us")
  end

  def contact
    @country = params[:country]
    @phone_number = case @country

    when "us", "ca"
      "(800) 555-6789"
    when "uk"
      "(020) 7946 1234"
    else
      "+1 (987) 654-3210"
    end

    render("demo/contact_us")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @subjects = Subject.order("position ASC")
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new
  end

  def create
    # instantiate a new obj using form params
    @subject = Subject.new(subject_params)
    # save the obj
    if @subject.save
      # if save succeeds, redirect tot he index action
      redirect_to(subjects_path)
    else
      # If save fails, redisplay the form so user can fix problems
      render("new")
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update(subject_params)
      redirect_to(subject_path(@subject))
    else
      render("edit")
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    redirect_to(subjects_path)
  end

  private
    def subject_params
      params.require(:subject).permit(:name, :visible, :position)
    end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end

  def route
  end

  def user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    render(partial: "application/error_messages", locals: { object: object })
  end
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/application/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div id="error-explanation">
    <h2><%= pluralize(object.errors.size, "error") %> prohibited this record from being saved</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/demo/about_us.html.erb
<h1>This is the About Us page</h1>
<br/>
<%= link_to('Contact Us', :action => "contact", :country => 'us')%>

app/views/demo/contact_us.html.erb
<h1>This is the Contact Us page</h1>
<br/>
<%= link_to('About Us', :action => "about")%>
<br/>
Phone Number: <%= @phone_number %>
<br/>
Press: <%= mail_to("press@nowhere.com")%>
<%= @country %>

app/views/demo/hello.html.erb
<h1>This is the Hello Page</h1>

<%= 1 + 1 %>

<br />

<% target = 'world' %>

<%= "Hello #{target}!" %>

<br />

<% @array.each do |n| %>
    <p><%= n %></p>
<% end %>

<br />

<%= link_to("Index page", {:action => 'index'}) %>

<br />

ID: <%= @id %><br/>
ID: <%= params[:id] %> <br/>
Page: <%= @page %>

app/views/demo/index.html.erb
<h1>Hello World!</h1>
<p>index page</p>
<a href="/demo/hello">Hello page 1</a>
<br/>

<%= link_to("Hello page 2", {:action => 'hello'}) %>

<br />

<%= link_to("Hello with parameters", {:action => 'hello', :page => 5, :id => 20}) %>

<br/>

<%= link_to("All Subjects", subjects_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Simple Cms" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/delete.html.erb
<h1>Pages#delete</h1>
<p>Find me in app/views/pages/delete.html.erb</p>

app/views/pages/edit.html.erb
<h1>Pages#edit</h1>
<p>Find me in app/views/pages/edit.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/new.html.erb
<h1>Pages#new</h1>
<p>Find me in app/views/pages/new.html.erb</p>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>

app/views/subjects/_form.html.erb
    <%= error_messages_for(f.object) %>
    
    <table summary="Subject form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.text_field(:position) %></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.text_field(:visible) %></td>
      </tr>
    </table>

app/views/subjects/delete.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects delete">
  <h2>Delete Subject</h2>

<% # can also just do form_for(@subject), rails is smart enought to decipher what to do %>
  <%= form_for(@subject, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this subject?</p>
    <p><%= @subject.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/edit.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects edit">
  <h2>Update Subject</h2>

  <%= form_for(@subject) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/index.html.erb
<div class="subjects index">
  <h2>Subjects</h2>

  <%= link_to("Add New Subject", new_subject_path, :class => 'action new') %>

  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
    <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.position %></td>
      <td><%= subject.name %></td>
      <td class="center"><%= subject.visible ? 'Yes' : 'No' %></td>
      <td class="center"><%= subject.pages.size %></td>
      <td class="actions">
        <%= link_to("Show", subject_path(subject), :class => 'action show') %>
        <%= link_to("Edit", edit_subject_path(subject), :class => 'action edit') %>
        <%= link_to("Delete", delete_subject_path(subject), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/subjects/new.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects new">
  <h2>Create Subject</h2>

<% # can also just do form_for(@subject), rails is smart enought to decipher what to do %>
  <%= form_for(@subject, :url => subjects_path, :method => 'post') do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/show.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Subject</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @subject.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>

</div>